import os
import time
import random
from datetime import datetime

SHARED_DIR = "./shared_file_storage"

def main():
    print("[#] File generation initiated.")
    os.makedirs(SHARED_DIR, exist_ok=True)

    while True:
        wait = random.randint(30, 60)
        time.sleep(wait)

        filename = f"file_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.txt"
        filepath = os.path.join(SHARED_DIR, filename)

        with open(filepath, "w") as f:
            f.write("This file was generated as a part of a home assignment for an interview to SeeTrue AI. \n " \
            "The file was generated by a python script that the candidate Yoav Katz wrote. \n" * 100)

        print(f"[#] Created file: {filepath}")


if __name__ == "__main__":
    main()
